name: Khabar
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  another_flutter_splash_screen: ^1.2.0
  google_fonts: 6.1.0
  cached_network_image: ^3.3.1
  animated_custom_dropdown: ^3.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  timeago: ^3.6.1
  flutter_screenutil: ^5.9.0
  url_launcher:






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: "launcher_icon"
  ios: true


  flutter_lints: ^2.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/


